export const CONNECTION_WEBSOCKET = 'CONNECTION_WEBSOCKET';
export const CREATE_SESSION = 'CREATE_SESSION';
export const WAITING_FOR_PARTICIPANTS = 'WAITING_FOR_PARTICIPANTS';
export const VOTE_IN_PROGRESS = 'VOTE_IN_PROGRESS';
export const VOTE_FINISHED = 'VOTE_FINISHED';
